config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {
  omniauth_callbacks: 'users/omniauth_callbacks'}
  root "pages#home"
  # Defines the root path route ("/")
  resources :desks do
    collection do
      get :load_more
      get :render_search_results
    end
    resources :messages, only: [:new, :create]
    resource :follows, only: [:create, :destroy]
  end
  resources :rooms do
    post "invite/:user_id", to: "invites#create", as: :invite
    post "update_youtube", to: "rooms#update_youtube"
    resources :chatmessages, only: :create
    resources :polls, only: [:create, :edit, :update] do
      resources :ballots, only: :create
    end
    collection do
      get :render_search_results
    end
  end
  get "/my_rooms", to: "rooms#my_rooms"

  resources :spots
  resources :votes, only: [:create] do
    delete "/", to: "votes#destroy", on: :collection
  end

  post "/update_user_last_online", to: "application#update_user_last_online"
  get "/followed_users_status", to: "application#followed_users_status"
end

app/views/shared/_card.html.erb
<% desk_obj = desk %> <%# this `desk` refers to OpenStruct %>
<% d = desk_obj.desk %>
<% status = desk_obj.status %>

<div class="index-card" data-controller="message" style="background-image: url('https://res.cloudinary.com/dawxkhlcq/image/upload/v1743781242/desk2_mmzyzu.png');" data-message-target="clickable-card" data-action="click->message#toIndividualDesk" data-url="<%= desk_path(d) %>">
  <div class="card-title"><%= d.title %></div>
  <div class="card-username"><%= "@#{d.user.username}" %> <%= status %> </div>
  <div class="card-tasks">📚Interest: <%= d.interest %></div>
  <% if current_user %>
  <% if current_user.favorited?(d) %>
  <div class="desk-index-status">🐝 Followed</div>
  <% end %>
  <% end %>
</div>

app/views/shared/_create_hive_button.html.erb
<%=link_to new_room_path, class: "btn create-hive-btn" do %>
<div>Create a new hive <i class="fa-regular fa-square-plus"></i></div>
<% end %>

app/views/shared/_flashes.html.erb
<div data-controller="shared--flash" class="flash-wrapper">
  <% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
  <% end %>
  <% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="bg-body-tertiary text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3 footer">
    © 2025 Copyright: StudyHive.com
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_kanban.html.erb
<h1>Today's Tasks</h1>
<ul>
  <li>
    <h3> Make copies of the worksheets</h3>
  </li>
  <li>
    <h3> Grade the quizzes</h3>
  </li>
  <li>
    <h3> Prepare the lesson plan for tomorrow</h3>
  </li>
  <li>
    <h3> Practice, practice, practice</h3>
  </li>
  <li>
    <h3> Get ready for the meeting</h3>
  </li>
</ul>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbar-background sticky-top px-3">
  <%= link_to root_path, class: "navbar-brand d-flex align-items-center justify-content-center" do %>
  <%= image_tag "https://res.cloudinary.com/dawxkhlcq/image/upload/v1743781763/navbarlogo_pfgiji.png", class: "navbar-logo"%>
  <% end %>
  <button class="navbar-toggler" type="button" data-turbo="false" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <% if current_user&.desk  %>
        <%=link_to "My Desk", desk_path(current_user.desk), class: "nav-link navbar-text"%>
        <% end %>
      </li>
      <li class="nav-item active">
        <%=link_to "Desks", desks_path, class: "nav-link navbar-text"%>
      </li>
      <li class="nav-item">
        <%=link_to "Hives", rooms_path, class: "nav-link navbar-text"%>
      </li>
      <li class="nav-item">
        <%=link_to "My hives", my_rooms_path, class: "nav-link navbar-text"%>
      </li>
    </ul>
    <div class="d-none d-md-flex ms-auto gap-2">
      <% if current_user %>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn home-custom-sign-btn navbar-text" %>
      <% else %>
      <%= link_to "Sign Up", new_user_registration_path, class: "nav-link navbar-text" %>
      <%= link_to "Log In", new_user_session_path, class: "nav-link navbar-text" %>
      <% end %>
    </div>
    <div class="d-flex flex-column d-md-none ms-auto">
      <% if current_user %>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn home-custom-sign-btn navbar-text" %>
      <% else %>
      <%= link_to "Sign Up", new_user_registration_path, class: "nav-link navbar-text" %>
      <%= link_to "Log In", new_user_session_path, class: "nav-link navbar-text" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_resources_list.html.erb
<%= turbo_frame_tag "resources-list" do %>
    <% room.res_list.each_with_index do |item, idx| %>
      <div class="d-flex align-items-center">
        <% if user == "owner" %>
          <%= form_with url: room_path(room), method: :patch do |f| %>
            <%= f.hidden_field :idx_to_remove, value: idx %>
            <%= f.submit "-", class: "resources-remove-button" %>
          <% end %>
        <% end %>

        <a href="<%= item %>" target="_blank"><%= item %></a>
      </div>
    <% end %>
  <% end %>

app/views/shared/_resources_submit_form.html.erb
<%= turbo_frame_tag "resources-submit-form" do %>
  <% if user == "owner" %>
    <%= form_with url: room_path(room), method: :patch do |f| %>
      <div class="resources-form">
        <%= f.text_field :input_field, class: "resources-input", placeholder: "Add a new resource link", required: true %>
        <%= f.submit "+", class: "resources-button" %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_roomcard.erb
<div class="card col-sm-6 col-md-4 room-index-card room-animation-card hex-card d-flex flex-column align-items-center">
  <div class="d-flex flex-column align-items-center room-card-body">
    <div class="room-card-title d-flex align-items-center text-center justify-content-center mb-2 mt-2"><%=room.title%></div>
    <div class="card-text"><strong><%=room.user.username%></strong></div>
    <div class="card-text"><strong><%=room.public ? "Public" : "Private"%></strong></div>
    <div class="card-text"><strong><%= room.spots.length > 1 ? "#{room.spots.length} members" : "#{room.spots.length} member" %></strong></div>
    <% if status_text.present? %>
      <div class="card-text"><strong><%= status_text %></strong></div>
    <% end %>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<div class="search-container">
  <%= form_with url: path, method: :get, data: { turbo_stream: true }, local: false, class: "search-form" do %>
    <select name="search_type" class="search-select">
      <option value="title" <%= "selected" if params[:search_type].nil? || params[:search_type] == "title" %>><%= title_name %></option>
      <option value="user" <%= "selected" if params[:search_type] == "user" %>><%= user_name %></option>
    </select>
    <%= text_field_tag :query, params[:query], placeholder: "  Search by title or username...", class: "search-input" %>
    <%= submit_tag "🔍", class: "search-button" %>
  <% end %>
</div>