config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {
  omniauth_callbacks: 'users/omniauth_callbacks'}
  root "pages#home"
  # Defines the root path route ("/")
  resources :desks do
    collection do
      get :load_more
      get :render_search_results
    end
    resources :messages, only: [:new, :create]
    resource :follows, only: [:create, :destroy]
  end
  resources :rooms do
    post "invite/:user_id", to: "invites#create", as: :invite
    post "update_youtube", to: "rooms#update_youtube"
    resources :chatmessages, only: :create
    resources :polls, only: [:create, :edit, :update] do
      resources :ballots, only: :create
    end
    collection do
      get :render_search_results
    end
  end
  get "/my_rooms", to: "rooms#my_rooms"

  resources :spots
  resources :votes, only: [:create] do
    delete "/", to: "votes#destroy", on: :collection
  end

  post "/update_user_last_online", to: "application#update_user_last_online"
  get "/followed_users_status", to: "application#followed_users_status"
end

app/models/desk.rb
class Desk < ApplicationRecord
  belongs_to :user
  has_many :events, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :favorites, as: :favoritable, dependent: :destroy

  before_create :set_default_image
  acts_as_favoritable

  private

  def set_default_image
    # if image is null, then set to desk1 image
    self.image ||= "desk2 - Copy.png"
  end
end

app/controllers/desks_controller.rb
class DesksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_desk_and_user, only: [:show]
  before_action :set_basic_info, only: [:show]
  PER_PAGE = 4
  def index
    # get the page params
    @page = (params[:page] || 1).to_i
    search_results
  end
  def show
    @message = Message.new

    if params.keys.count > 3
      @query =  params["desk"]["question"]
      openai_service = OpenaiService.new
      @response = openai_service.generate_response(@query)
    end

  end

  def load_more
    @page = params[:page].to_i
    search_results
    @has_more_pages = @all_desks.count > @page * PER_PAGE
    page = @page

    respond_to do |format|
      format.turbo_stream do
        render :load_more_results, locals: { desks: @desks, page: page, has_more_pages: @has_more_pages }  # loading in turbo stream
      end
      format.html { render plain: "HTML fallback triggered" }
    end
  end
  def update
    @desk = Desk.find(params[:id])
    @desk.update(desk_params)
    redirect_to desk_path(@desk)
  end

  def render_search_results
    @page = (params[:page] || 1).to_i
    # everytime we press the button, there will be ten more new data
    search_results
    respond_to do |format|
      # just in case user tried to type in the url manually
      format.html { render plain: "Wrong URL" }
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
        "search_results",
        partial: "desks/search_results",
        locals: { desks: @desks, all_desks: @all_desks }
      )
      end
    end
  end

  private

  def search_results
    query = params[:query].strip if params[:query].present?
    type = params[:search_type]
    base_scope =
      if query.present?
        case type
        when "title"
          Desk.where("title ~* ?", "\\m#{params[:query]}\\M")
        when "user"
          Desk.joins(:user).where("users.username  ~* ?", "\\m#{params[:query]}\\M")
        end
      else
        Desk.all
      end
    @desks = base_scope.limit(PER_PAGE).offset((@page - 1) * PER_PAGE) #only loading new data
    @all_desks = base_scope.all
    @desks = @desks.map do |desk|
      status = desk.user.last_online_at.present? && desk.user.last_online_at > 30.minutes.ago ? "🟢 Online" : "🔴 Offline"
      OpenStruct.new(desk: desk, status: status)
    end
  end

  def set_desk_and_user
    if Desk.exists?(id: params[:id])
      @desk = Desk.find(params[:id])
      @user = @desk.user
    else
      @desk = current_user.desk
      @user = current_user
    end
  end

  def set_basic_info
    @online_status = @desk.user.last_online_at.present? && @desk.user.last_online_at > 30.minutes.ago
    @active_spot = @desk.user.spots.includes(:room).where(active: true).first
    @if_in_room = @active_spot.present?

    if @active_spot
      @room_status = @active_spot.room&.public ? "Public" : "Private"
      @room_title = @active_spot.room&.title
    else
      @room_status = nil
      @room_title = nil
    end
  end

  def desk_params
    params.require(:desk).permit(:title, :intro, :interest, :question)
  end
end

app/views/desks/_desk_message.html.erb
<div class="message">
  <span><strong>
      <%= link_to message.user.username, desk_path(message.user.desk) %></strong></span>: <span class="text-break"><%= message.text %></span>
  <p><%= message.created_at.strftime("%d/%m/%Y %H:%M:%S") %></p>
</div>

app/views/desks/_edit.html.erb
<%= simple_form_for @desk do |f| %>
    <%= f.input :title, label: "What's your task today?", input_html: { class: "desk-show-edit-column" } %>
    <%= f.input :intro, label: "Tell us about yourself!", input_html: { class: "desk-show-edit-column" } %>
    <%= f.input :interest, label: "What are you interested in the most recently?", input_html: { class: "desk-show-edit-column" } %>
    <%= f.input :question, label: "What's the question hovering in your mind recently?", input_html: { class: "desk-show-edit-column" } %>
    <%= f.button :submit %>
<% end %>

app/views/desks/_search_results.html.erb
<div id="search_results">
  <div id="desk_list" class="d-flex flex-wrap justify-content-center">
    <% if desks.empty? %>
    <div class="desk-index-no-results-text mb-4">No desks found</div>
    <% else %>
    <% desks.each do |desk| %>
    <%= render "shared/card", desk: desk %>
    <% end %>
    <% end %>
  </div>
  <% if @all_desks.count > @desks.count %>
  <%= link_to "Load More 🐝", load_more_desks_path(page: 2, query: params[:query], search_type: params[:search_type]), data: { turbo_stream: true }, class: "btn btn-primary mt-3", id: "load_more_button" %>
  <% end %>
</div>

app/views/desks/_show_ai_bee.html.erb
<div data-controller="toggle-ai">
  <div id="ai-chat-div" data-toggle-ai-target="aiChat" class="<%= "d-none" unless @response %>  ">
    <h3>Ask the AI Queen Bee</h3>
    <%= simple_form_for @desk, method: :get do |f| %>
      <div class="d-flex">
        <%= f.input :question, label: false, wrapper: false %>
        <button type="submit" class="chat-send-btn">
          <i class="fas fa-paper-plane"></i>
        </button>
      </div>
    <% end %>
    <% if @query %>
      <div class="ai-response">
        <p><strong>
            Your question: </strong><%= @query %>
        </p>
        <p>--------------------</p>
        <p><strong>
            The Queen Bee Response: </strong><%= @response %>
        </p>
      </div>
    <% end %>
  </div>
  <div class="queen-bee-img" data-action="click->toggle-ai#showHideAI"></div>
</div>

app/views/desks/_show_sticky_notes.html.erb
<div class="sticky-notes" data-controller="sticky-notes">
  <% @desk.messages.last(5).each do |message| %>
    <div class="sticky-note">
      <p id="sticky-time"><%= message.created_at.strftime("%m/%d %H:%M") %></p>
      <p class="text-break" data-sticky-note-target="message-content"><%= message.text %></p>
      <p class="align-self-end"><em>
          - <%= message.user.username %></em></p>
    </div>
  <% end %>
</div>

app/views/desks/_show_toggle_messages.html.erb
<div data-controller="toggle-messages">
  <button data-action="click->toggle-messages#showHideMessages"><i class="fa-regular fa-message"></i>&nbsp;Message</button>
  <div class="messages-main" data-toggle-messages-target="messages">
    <div id="messages-div" >
      <!-- Messages -->
      <div >
        <% @desk.messages.each do |message| %>
          <%= render("desk_message",{ message: message}) %>
        <% end %>
      </div>
    </div>
    <div class="clickable-div mt-2">
      <!-- Hidden Form -->
      <div class="form-container" data-toggle-messages-target="form">
        <%= simple_form_for [@desk, @message],
        method: :post,
        html: {class: "d-flex",
        data: { controller: "reset-form",
        action: "turbo:submit-end->reset-form#reset" }},
        data: {
        turbo_frame: "messages"
        } do |f| %>
          <div class="d-flex">
            <%= f.input :text,
                label: false,
                wrapper: false,
                placeholder: "Message from #{current_user.username}",
                input_html: { id: "msg_content", class: "chat-input" } %>
            <button type="submit" class="chat-send-btn">
              <i class="fas fa-paper-plane"></i>
            </button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/desks/_show_user_bar.html.erb
<div class="desk-show-info-btns d-flex flex-column" data-controller="edit-desk">
  <div style="position: relative;">
    <button data-action="click->edit-desk#edit"><i class="fa-solid fa-pen-to-square desk-show-edit-btn"></i>&nbsp;Edit</button>
    <div class="desk-edit-form d-none" data-edit-desk-target="form">
      <%= render "desks/edit"%>
    </div>
  </div>
  <% if current_user.favorited?(@desk) %>
    <%= button_to desk_follows_path(@desk), method: :delete, data: { action:"click->follows#unfollow", follows_target: "followButton", controller: "follows", confirm: "Are you sure you want to unfollow?" } do %>
      <i class="fa-solid fa-heart"></i>&nbsp;Unfollow
    <% end %>
  <% else %>
    <%= button_to desk_follows_path(@desk), method: :post, data: { action:"click->follows#follow", follows_target: "followButton", controller: "follows" } do %>
      <i class="far fa-heart"></i>&nbsp;Follow
    <% end%>
  <% end %>
  <%= render "show_toggle_messages" %>
</div>

app/views/desks/_show_user_headshot.html.erb
<div class="desk-show-shot">
  <%= image_tag "https://res.cloudinary.com/dawxkhlcq/image/upload/v1743781340/headshot_ue4nqf.png", class: "desk-show-headshot" %>
</div>

app/views/desks/_show_user_info.html.erb
<div class="desk-show-intro">
  <div class="desk-show-about-me">
    <div style="font-weight: bold;"><i class="fa-solid fa-bookmark"></i>&nbsp;About Me</div>
    <%= @desk.intro%>
  </div>
  <div class="desk-show-current-interest">
    <div style="font-weight: bold;"><i class="fa-solid fa-book-open"></i>&nbsp;I'm currently interested in...</div>
    <%= @desk.interest%>
  </div>
  <div class="desk-show-question">
    <div style="font-weight: bold;"><i class="fa-solid fa-question"></i>&nbsp;I want to ask...</div>
    <%= @desk.question %>
  </div>
</div>

app/views/desks/_show_user_title_status.html.erb
<div class="desk-show-name-and-status d-flex flex-column">
  <div class="desk-show-title mb-0">
    <h2><%= @desk.title %></h2>
  </div>
  <div class="desk-show-status mb-0">
    <p class="desk-show-status-username"><%= "@#{@desk.user.username}" %></p>
    <p><%= @online_status ? "🟢 Online #{ @room_status.nil? ? 'not in any rooms right now' : "in #{@room_status ? 'Public' : 'Private'} Room #{@room_title}" }" : "🔴 Offline" %></p>
  </div>
</div>

app/views/desks/index.html.erb
<div class="index-desk-bg d-flex flex-column align-items-center">
  <div class="d-flex justify-content-center align-items-center">
    <div class="blackboard-container">
      <%= image_tag "https://res.cloudinary.com/dawxkhlcq/image/upload/v1743779624/blackboard1_idmlyr.png", class: "blackboard-img", alt: "Blackboard" %>
      <div class="blackboard-text-container" data-controller="blackboard"></div>
    </div>
  </div>
  <%= render "shared/searchbar", path: render_search_results_desks_path, title_name: "Desk Title", user_name: "Desk User" %>
  <div class="d-flex flex-column align-items-center">
      <%= render "search_results", all_desks: @all_desks, desks: @desks, online_status: @online_status %>
  </div>
</div>

app/views/desks/load_more_results.turbo_stream.erb
<%= turbo_stream.append "desk_list" do %>
  <%= render partial: "shared/card", collection: desks, as: :desk %>
<% end %>

<%= turbo_stream.replace "load_more_button" do %>
  <% if has_more_pages %>
      <%= link_to "Load More 🐝", load_more_desks_path(page: page + 1, query: params[:query], search_type: params[:search_type]), data: { turbo_stream: true }, class: "btn btn-primary mt-3", id: "load_more_button" %>
  <% end %>
<% end %>

app/views/desks/show.html.erb
<div class="d-flex flex-row show-desk-bg" style="padding-bottom: 150px;">
  <div class="desk-show-info-wrap d-flex flex-column col-6">
    <div class="desk-show-shot-and-name d-flex flex-row align-items-center justify-content-center">
      <%= render "show_user_headshot" %>
      <%= render "show_user_title_status" %>
    </div>
    <div class="d-flex flex-row justify-content-center desk-show-bottom">
      <%= render "show_user_bar" %>
      <%= render "show_user_info" %>
    </div>
  </div>
  <div class="desk-img col-6">
    <%= render "show_sticky_notes"%>
    <%= render "show_ai_bee"%>
  </div>
</div>