config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {
  omniauth_callbacks: 'users/omniauth_callbacks'}
  root "pages#home"
  # Defines the root path route ("/")
  resources :desks do
    collection do
      get :load_more
      get :render_search_results
    end
    resources :messages, only: [:new, :create]
    resource :follows, only: [:create, :destroy]
  end
  resources :rooms do
    post "invite/:user_id", to: "invites#create", as: :invite
    post "update_youtube", to: "rooms#update_youtube"
    resources :chatmessages, only: :create
    resources :polls, only: [:create, :edit, :update] do
      resources :ballots, only: :create
    end
    collection do
      get :render_search_results
    end
  end
  get "/my_rooms", to: "rooms#my_rooms"

  resources :spots
  resources :votes, only: [:create] do
    delete "/", to: "votes#destroy", on: :collection
  end

  post "/update_user_last_online", to: "application#update_user_last_online"
  get "/followed_users_status", to: "application#followed_users_status"
end

app/models/poll.rb
class Poll < ApplicationRecord
  has_many :poll_options, dependent: :destroy
  has_many :ballots, dependent: :destroy
  belongs_to :user
  belongs_to :room

  def user_voted?(user)
    ballots.exists?(user_id: user.id)
  end
  def total_votes
    poll_options.sum { |option| option.votes_for.size }
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :spots, dependent: :destroy
  has_many :chatmessages, dependent: :destroy
  has_many :polls, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :invites, dependent: :destroy

  after_create :create_spot_for_owner
  # after_commit :broadcast_message

  private

  def create_spot_for_owner
    spots.create(user: user, status: :accepted)
  end

  def broadcast_message
    broadcast_append_to "room_#{room.id}_resources",
                        partial: "shared/resources"
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def new
    @room = Room.new
  end

  def create
    @room = Room.new(rooms_params)
    @room.user_id = current_user.id

    if @room.save
      redirect_to rooms_path, notice: "Room is built successfully!"
    else
      puts @room.errors.full_messages
      render "new", alert: "Failed sending message"
    end
  end

  def index
    raw_rooms = Room.all
    @desk = current_user.desk
    @rooms = show_all_rooms(raw_rooms)
  end

  # render all hives
  def render_search_results
    query = params[:query].strip if params[:query].present?
    type = params[:search_type]
    if query.present?
      case type
      when "title"
        raw_rooms = Room.where("title ~* ?", "\\m#{params[:query]}\\M").all
      when "user"
        raw_rooms = Room.joins(:user).where("users.username  ~* ?", "\\m#{params[:query]}\\M").all
      end
    else
        raw_rooms = Room.all
    end
    @rooms = show_all_rooms(raw_rooms)
    respond_to do |format|
      # just in case user tried to type in the url manually
      format.html { render plain: "Wrong URL" }
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
        "search_results",
        partial: "rooms/rooms_index_search_results",
        locals: { rooms: @rooms }
      )
      end
    end
  end

  def show
    @room = Room.find(params[:id])
    @all_users = User.all.where.not(id: current_user.id)
    @spot_current_user = Spot.find_by(user: current_user, room: @room)
    @participant_type = participant_type

    if @room.public == false && (@spot_current_user.nil? || @spot_current_user.status != "accepted")
      redirect_to rooms_path, alert: "You cannot enter this private room unless your spot is accepted."
      return
    end

    @chatmessage = Chatmessage.new
    @max_likes = @room.chatmessages.order(cached_votes_up: :desc).limit(1).pluck(:cached_votes_up).first
    @chatmessages_most_liked = Chatmessage.where(cached_votes_up: @max_likes)
    @poll = Poll.new
    @all_polls = @room.polls.includes(:poll_options).sort_by { |poll| poll.user_voted?(current_user) ? 1 : 0 }
    @notifications = Notification.where(room: @room).order(created_at: :desc)

    @spot_current_user.update(active: true) if @spot_current_user.present?
    @spots_accepted = Spot.where(status: :accepted, room: @room)

  end

  def update_youtube
    @room = Room.find(params[:room_id])
    youtube_url = params[:youtube_id]

    unless youtube_url.present?
      redirect_to @room, alert: "Please enter a YouTube link."
      return
    end

    youtube_info = extract_youtube_id(youtube_url)
    unless youtube_info
      redirect_to @room, alert: "Invalid YouTube link."
      return
    end

    if @room.update(youtube_id: youtube_info[:id], youtube_start_time: youtube_info[:time])
      Notification.create(category: "youtube", user: current_user, room: @room)
      redirect_to @room, notice: "YouTube video updated."
    else
      render :show
    end

  end
  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    unless params[:idx_to_remove].present? || params[:input_field].present?
      @room.update(rooms_params)
      redirect_to room_path @room
      return
    end

    if params[:input_field].present?
      @room.res_list << params[:input_field]
    else
      @room.res_list.delete_at(params[:idx_to_remove].to_i)
    end

    if @room.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace("resources-submit-form",
              partial: "shared/resources_submit_form",
              locals: { room: @room, user: "owner" }),
            turbo_stream.replace("resources-list",
              partial: "shared/resources_list",
              locals: { user: "owner", room: @room })
          ]
        end
      end
      broadcast_update
    else
      redirect_to room_path @room
    end
  end

  def my_rooms
    @rooms_member = []
    @rooms_owned = []
    current_user.spots.each do |spot|
      room = spot.room
      room.user == current_user ? @rooms_owned << room : @rooms_member << room
    end
    @rooms_owned = show_all_rooms(@rooms_owned)
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_path
  end

  private

  def rooms_params
    params.require(:room).permit(:title, :locked, :public, :res_list, :youtube_id)
  end

  def broadcast_update
    # broadcast to the page that has turbo_stream tag of below channel name
    @room.broadcast_replace_to("room_#{@room.id}_resources/member",
                        target: "resources-list",
                        partial: "shared/resources_list",
                        locals: { user: "member", room: @room })
  end

  def participant_type
    (current_user == @room.user ? "owner" : "member")
  end

  def show_all_rooms(rooms)
    rooms = rooms.map do |room|
      is_entering_allowed = false
      room_status_text = nil

      if (room.public == true && room.locked == false) || room.user == current_user
        is_entering_allowed = true
      elsif room.public == false && room.locked == false && Spot.exists?(room: room, user: current_user, status: :pending)
        is_entering_allowed = false
        room_status_text = "Join request has been sent."
      elsif room.public == false && room.locked == false && Spot.exists?(room: room, user: current_user, status: :accepted)
        is_entering_allowed = true
      elsif room.public == false && room.locked == false
        is_entering_allowed = false
      elsif room.locked == true
        is_entering_allowed = false
        room_status_text = "Sorry this room is locked."
      end
      OpenStruct.new(room: room, status: is_entering_allowed, status_text: room_status_text)
    end
  end

  def extract_youtube_id(url)
    return nil if url.blank?

    begin
      # Parse the URL to extract the host, path, and query parameters
      uri = URI.parse(url)
    rescue URI::InvalidURIError
      return nil
    end

    host = uri.host&.downcase
    id = nil
    time = nil

    case host
    when "youtu.be"
      # e.g. https://youtu.be/abc123XYZ?t=90
      id = uri.path[1..]
      time = CGI.parse(uri.query.to_s)["t"]&.first
    when "www.youtube.com", "youtube.com", "m.youtube.com"
      params = CGI.parse(uri.query.to_s)

      if uri.path == "/watch"
        id = params["v"]&.first
        time = params["t"]&.first || params["start"]&.first
      elsif uri.path.start_with?("/embed/")
        id = uri.path.split("/")[2]
        time = params["start"]&.first
      elsif uri.path.start_with?("/shorts/")
        id = uri.path.split("/")[2]
      end
    end

    return nil unless id

    { id: id, time: time }
  end

end

app/views/rooms/show/_invitation_button.html.erb
<% if current_user == @room.user %>
  <div data-controller="invite">
    <i class="fa-solid fa-envelope room-show-invite" data-action="click->invite#toggle"></i>
    <div class="d-none room-show-invite-list" data-invite-target="section">
      <%= render "rooms/show/invitation_list" %>
    </div>
  </div>
<% end %>

app/views/rooms/show/_invitation_list.html.erb
<div class="d-flex flex-column" data-controller="invite">
  <% @all_users.each do |user| %>
    <div class="d-flex flex-row justify-cotent-between align-items-center">
      <div class="room-show-invite-info">
        <% if user.last_online_at.present? %>
          <% time_difference = Time.now - user.last_online_at %>
          <% online_status = time_difference < 30.minutes ? true : false %>
        <% else %>
          <% online_status = false %>
        <% end %>
        <p><span style="<%= online_status ? "" : "filter: grayscale(100%)" %>">🐝</span>
        <%= user.username %> <span style="font-size: 15px; font-style: italic; color: grey;">interest: <%= user.desk.interest %></span></p>

      </div>
      <%= button_to "invite", room_invite_path(room_id: @room.id, user_id: user.id), method: :post, data: { action: "click->invite#disable"}, class: "room-show-invite-btn" %>
    </div>
  <% end %>
</div>

app/views/rooms/show/_new_poll.html.erb
<div class="new-poll">
  <%= simple_form_for @poll, url: room_polls_path(@room) do |f| %>
    <div>
      <%= f.input :question, label: "Question:" %>
    </div>

    <div>
      <%= f.input :deadline, as: :datetime, label: "Deadline" %>
    </div>

    <div>
      <%= label_tag "Options(maximum: 4)" %>
      <% 4.times do |i| %>
        <%= text_field_tag "poll[options][]", nil, placeholder: "Option #{i+1}" %>
      <% end %>
    </div>
    <%= f.submit "Create Poll", class: "poll-btn"%>
  <% end %>
</div>

app/views/rooms/show/_old_poll.html.erb
<div id="poll_<%= poll.id %>" class="poll-container">
  <h3><%= poll.question %></h3>
  <p class="poll-deadline">🗓️ Deadline: <%= poll.deadline %></p>

  <% total_votes = poll.total_votes %>

  <% poll.poll_options.each do |option| %>
    <% percentage = total_votes > 0 ? (option.get_likes.size.to_f / total_votes * 100).round(1) : 0 %>

    <div class="poll-option">
      <div class="vote-button">
        <% if poll.user_voted?(current_user) %>
          <i class="fa-solid fa-circle-check"></i>
        <% else %>
          <button class="vote-btn">Vote</button>
        <% end %>
      </div>

      <div class="flex-column d-flex option-bar">
        <span class="poll-option-text"><%= option.option_text %></span>

        <div class="progress-bar-container">
          <div class="progress-bar" style="width: <%= percentage %>%"></div>
        </div>
      </div>

      <span class="percentage-badge"><%= percentage %>%</span>
    </div>
  <% end %>

  <% if poll.user_voted?(current_user) %>
    <p class="vote-confirmation"><i class="fa-solid fa-check" style="color: #FFD43B;"></i> You have voted</p>
  <% end %>
</div>

app/views/rooms/show/_poll.html.erb
<% if !poll.user_voted?(current_user) %>
    <div id="poll_<%= poll.id %>" class="room-tab-poll">
    <h3><%= poll.question %></h3>
    <i style="color: grey;">Deadline: <%= poll.deadline %></i>
    <%= form_with model: Ballot.new, url: room_poll_ballots_path(@room, poll), method: :post, data: { turbo: "true" } do |f| %>
      <% poll.poll_options.each do |option| %>
        <div class="polling-option">

          <%= check_box_tag "ballot[poll_option_ids][]", option.id, false, id: "option_#{option.id}", class: "poll-checkbox" %>


          <label for="<%= "option_#{option.id}" %>" class="poll-label">
            <%= option.option_text %>
          </label>
        </div>
      <% end %>


    <%= f.submit "Submit", class: "poll-btn"%>
    <% end %>
  </div>
<% else %>
  <%= render partial: "rooms/show/old_poll", locals: { poll: poll, input_html: { data: { ballot_target: "message" } } } %>
<% end %>

app/views/rooms/show/_room_owner_info.html.erb
<div class="room-show-user-description">
  <div class="room-show-user d-flex flex-row">
    <p class="mr-5">Owned by: <%=link_to @room.user.username, desk_path(@room.user) %></p>
    <p class="honey-icon">🍯</p>
  </div>
  <div class="mt-0 pt-o">
    <p style="color: grey"><%= @room.description %></p>
  </div>
</div>

app/views/rooms/show/_roomchat.html.erb
<div class="room-show-chat-title d-flex align-items-center">
  <div class="room-show-title-wrapper">
    <i class="fa-regular fa-comments"></i>Chat
  </div>
</div>
<div class="room-show-chat-container">
  <div class="room-show-chat">
    <div id="chatmessages">
    <% @room.chatmessages.each do |chatmessage| %>
      <%= render "chatmessages/chatmessage", chatmessage: chatmessage, liked: (current_user&.voted_for?(chatmessage) || false) %>
    <% end %>
    </div>
  </div>
  <div class="room-show-chat-input">
    <%= simple_form_for [@room, @chatmessage], html: {class: "chat-input-container d-flex", data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }} do |f| %>
      <div class="chat-input-wrapper flex-grow-1">
        <%= f.input :content,
              label: false,
              wrapper: false,
              placeholder: "Message from #{current_user.username}",
              input_html: { id: "msg_content", class: "chat-input", data: { action: "keydown.enter->reset-form#submit" } } %>
      </div>
      <button type="submit" class="chat-send-btn">
        <i class="fas fa-paper-plane"></i>
      </button>
    <% end %>
    <!-- Giphy search section -->
      <div data-controller="giphy" class="giphy-search-box">
        <button class="gif" data-action="click->giphy#open">GIF</button>
        <input type="text" data-giphy-target="input" placeholder="search GIF..." class="form-control d-none giphy-input" data-giphy-apikey-value="<%=ENV["GIPHY_API_KEY"]%>" data-action="input->giphy#search">
        <div data-giphy-target="results" class="giphy-results"></div>
      </div>
  </div>
</div>

app/views/rooms/show/_subscribe_button.html.erb
<% if current_user != @room.user %>
  <% unless @spot_current_user %>
    <%= button_to "Subscribe to this Hive!", spots_path(spot: { status: :accepted, active: true, room_id: @room.id, user_id: current_user.id }, redirect: room_path(@room)), method: :post, class: "room-show-btn" %>
  <% else @spot_current_user %>
    <%= button_to "Unsubsribe to this Hive!", spot_path(@spot_current_user, redirect: room_path(@room)), method: :delete, class: "room-show-btn", data: { confirm: "Are you sure you want to leave this room?" } %>
  <% end %>
<% end %>

app/views/rooms/show/_tabs.html.erb
<div class="tabs-div">
  <!-- Nav Tabs -->
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#hiveboard">
        <i class="fa-solid fa-tag"></i> Hiveboard
      </button>
    </li>
    <li class="nav-item">
      <button class="nav-link" data-bs-toggle="tab" data-bs-target="#resources">
        <i class="fa-solid fa-tag"></i> Resources
      </button>
    </li>
    <li class="nav-item">
      <button class="nav-link" data-bs-toggle="tab" data-bs-target="#hivepoll">
        <i class="fa-solid fa-tag"></i> HivePoll
      </button>
    </li>
    <li class="nav-item">
      <button class="nav-link" data-bs-toggle="tab" data-bs-target="#settings">
        <i class="fa-solid fa-tag"></i> Settings
      </button>
    </li>
    <li class="nav-item">
      <button class="nav-link" data-bs-toggle="tab" data-bs-target="#members">
        <i class="fa-solid fa-tag"></i> Members
      </button>
    </li>
  </ul>
  <!-- Tab Content -->
  <div class="tab-content">
    <div class="tab-pane fade show active" id="hiveboard">
      <%= render "shared/tabs/hiveboard" %>
    </div>
    <div class="tab-pane fade" id="resources">
      <%= render "shared/tabs/resources" %>
    </div>
    <div class="tab-pane fade" id="hivepoll">
      <%= render "shared/tabs/poll_container" %>
    </div>
    <div class="tab-pane fade" id="settings">
      <%= render "shared/tabs/settings" %>
    </div>
    <div class="tab-pane fade" id="members">
      <%= render "shared/tabs/members" %>
    </div>
  </div>
</div>

app/views/rooms/show/_youtube.html.erb
<div class="d-flex flex-column">
  <div>
    <% if current_user == @room.user %>
      <%= form_with url: room_update_youtube_path(@room), method: :post, local: true, class: "search-form d-flex align-items-center" do %>
        <%= text_field_tag :youtube_id, params[:youtube_id], placeholder: "Please enter Youtube URL...", class: "search-input flex-grow-1" %>
        <%= button_tag type: "submit", class: "search-button" do %>
            <i class="fas fa-paper-plane"></i>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="w-100 ratio ratio-16x9">
    <iframe class="w-100" src="https://www.youtube.com/embed/<%= @room.youtube_id %>?start=<%= @room.youtube_start_time %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
  </div>
</div>